# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.location::lang.models.area.label

# Model Form Field configuration
form: $/acorn/location/models/area/fields.yaml

# Model Class name
modelClass: Acorn\Location\Models\Area

# Default redirect location
defaultRedirect: acorn/location/areas

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/location/areas/update/:id
    redirectClose: acorn/location/areas

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/location/areas
    redirectClose: acorn/location/areas

# Preview page
preview:
    title: backend::lang.form.preview_title
