# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.location::lang.models.area.label

# Model Form Field configuration
form: $/acornassociated/location/models/area/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\Area

# Default redirect location
defaultRedirect: acornassociated/locations/areas

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/locations/areas/update/:id
    redirectClose: acornassociated/locations/areas

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/locations/areas
    redirectClose: acornassociated/locations/areas

# Preview page
preview:
    title: backend::lang.form.preview_title
