plugin:
    name: acorn.location::lang.plugin.name
    description: acorn.location::lang.plugin.description
    author: 'Acorn'
    icon: wn-building
    replaces: {  }
permissions:
    acorn_location:
        label: acorn.location::lang.permissions.manage_locations
        tab: acorn.location::lang.plugin.name
navigation:
    location-main-menu-item:
        label: acorn.location::lang.plugin.name
        url: acorn/location/locations
        icon: icon-building
        permissions:
            - acorn_location
        sideMenu:
            facilities:
                label: acorn.location::lang.models.location.label_plural
                url: acorn/location/locations
                icon: icon-building
            types:
                label: acorn.location::lang.models.type.label_plural
                url: acorn/location/types
                icon: icon-stripe
