plugin:
    name: acornassociated.location::lang.plugin.name
    description: acornassociated.location::lang.plugin.description
    author: 'Acorn Associated'
    icon: wn-building
    replaces: {  }
permissions:
    acornassociated_location:
        label: acornassociated.location::lang.permissions.manage_locations
        tab: acornassociated.location::lang.plugin.name
navigation:
    location-main-menu-item:
        label: acornassociated.location::lang.plugin.name
        url: acornassociated/location/locations
        icon: icon-building
        permissions:
            - acornassociated_location
        sideMenu:
            facilities:
                label: acornassociated.location::lang.models.location.label_plural
                url: acornassociated/location/locations
                icon: icon-building
            types:
                label: acornassociated.location::lang.models.type.label_plural
                url: acornassociated/location/types
                icon: icon-stripe
