# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.location::lang.models.type.label'

# Model Form Field configuration
form: $/acornassociated/location/models/type/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\Type

# Default redirect location
defaultRedirect: acornassociated/location/types

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/location/types/update/:id
    redirectClose: acornassociated/location/types

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/location/types
    redirectClose: acornassociated/location/types

# Preview page
preview:
    title: backend::lang.form.preview_title
