# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.location::lang.models.type.label'

# Model Form Field configuration
form: $/acorn/location/models/type/fields.yaml

# Model Class name
modelClass: Acorn\Location\Models\Type

# Default redirect location
defaultRedirect: acorn/location/types

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/location/types/update/:id
    redirectClose: acorn/location/types

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/location/types
    redirectClose: acorn/location/types

# Preview page
preview:
    title: backend::lang.form.preview_title
