# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.location::lang.models.address.label

# Model Form Field configuration
form: $/acornassociated/location/models/address/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\Address

# Default redirect location
defaultRedirect: acornassociated/locations/addresses

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/locations/addresses/update/:id
    redirectClose: acornassociated/locations/addresses

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/locations/addresses
    redirectClose: acornassociated/locations/addresses

# Preview page
preview:
    title: backend::lang.form.preview_title
