# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.location::lang.models.address.label

# Model Form Field configuration
form: $/acorn/location/models/address/fields.yaml

# Model Class name
modelClass: Acorn\Location\Models\Address

# Default redirect location
defaultRedirect: acorn/location/addresses

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/location/addresses/update/:id
    redirectClose: acorn/location/addresses

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/location/addresses
    redirectClose: acorn/location/addresses

# Preview page
preview:
    title: backend::lang.form.preview_title
