# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.location::lang.models.lookup.label'

# Model Form Field configuration
form: $/acornassociated/location/models/lookup/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\Lookup

# Default redirect location
defaultRedirect: acornassociated/location/lookups

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/location/lookups/update/:id
    redirectClose: acornassociated/location/lookups

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/location/lookups
    redirectClose: acornassociated/location/lookups

# Preview page
preview:
    title: backend::lang.form.preview_title
