# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.location::lang.models.lookup.label'

# Model Form Field configuration
form: $/acorn/location/models/lookup/fields.yaml

# Model Class name
modelClass: Acorn\Location\Models\Lookup

# Default redirect location
defaultRedirect: acorn/location/lookups

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/location/lookups/update/:id
    redirectClose: acorn/location/lookups

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/location/lookups
    redirectClose: acorn/location/lookups

# Preview page
preview:
    title: backend::lang.form.preview_title
