# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.location::lang.models.gps.label

# Model Form Field configuration
form: $/acornassociated/location/models/gp/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\GP

# Default redirect location
defaultRedirect: acornassociated/locations/gps

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/locations/gps/update/:id
    redirectClose: acornassociated/locations/gps

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/locations/gps
    redirectClose: acornassociated/locations/gps

# Preview page
preview:
    title: backend::lang.form.preview_title
