# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.location::lang.models.gps.label

# Model Form Field configuration
form: $/acorn/location/models/gp/fields.yaml

# Model Class name
modelClass: Acorn\Location\Models\GP

# Default redirect location
defaultRedirect: acorn/location/gps

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/location/gps/update/:id
    redirectClose: acorn/location/gps

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/location/gps
    redirectClose: acorn/location/gps

# Preview page
preview:
    title: backend::lang.form.preview_title
