name: Location
form: $/acornassociated/location/models/location/fields.yaml
modelClass: AcornAssociated\Location\Models\Location
defaultRedirect: acornassociated/location/locations
create:
    redirect: 'acornassociated/location/locations/update/:id'
    redirectClose: acornassociated/location/locations
update:
    redirect: acornassociated/location/locations
    redirectClose: acornassociated/location/locations
