ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS user_group_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_types DROP CONSTRAINT IF EXISTS types_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS type_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_types DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_area_types DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_addresses DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_gps DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS server_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_types DROP CONSTRAINT IF EXISTS parent_type_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS parent_area_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS locations_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_addresses DROP CONSTRAINT IF EXISTS gps_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS gps_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_gps DROP CONSTRAINT IF EXISTS gps_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS areas_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_area_types DROP CONSTRAINT IF EXISTS area_types_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS area_type_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_addresses DROP CONSTRAINT IF EXISTS area_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_addresses DROP CONSTRAINT IF EXISTS addresses_created_by_user;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS address_id;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_types DROP CONSTRAINT IF EXISTS location_types_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_locations DROP CONSTRAINT IF EXISTS location_locations_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_gps DROP CONSTRAINT IF EXISTS location_gps_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_areas DROP CONSTRAINT IF EXISTS location_areas_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_area_types DROP CONSTRAINT IF EXISTS location_area_types_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_addresses DROP CONSTRAINT IF EXISTS location_addresses_pkey;
ALTER TABLE IF EXISTS ONLY public.acornassociated_location_lookup DROP CONSTRAINT IF EXISTS acornassociated_location_location_pkey;
DROP TRIGGER IF EXISTS tr_acornassociated_location_types_server_id ON public.acornassociated_location_types;
DROP TRIGGER IF EXISTS tr_acornassociated_location_types_new_replicated_row ON public.acornassociated_location_types;
DROP TRIGGER IF EXISTS tr_acornassociated_location_locations_server_id ON public.acornassociated_location_locations;
DROP TRIGGER IF EXISTS tr_acornassociated_location_locations_new_replicated_row ON public.acornassociated_location_locations;
DROP TRIGGER IF EXISTS tr_acornassociated_location_gps_server_id ON public.acornassociated_location_gps;
DROP TRIGGER IF EXISTS tr_acornassociated_location_gps_new_replicated_row ON public.acornassociated_location_gps;
DROP TRIGGER IF EXISTS tr_acornassociated_location_areas_server_id ON public.acornassociated_location_areas;
DROP TRIGGER IF EXISTS tr_acornassociated_location_areas_new_replicated_row ON public.acornassociated_location_areas;
DROP TRIGGER IF EXISTS tr_acornassociated_location_area_types_server_id ON public.acornassociated_location_area_types;
DROP TRIGGER IF EXISTS tr_acornassociated_location_area_types_new_replicated_row ON public.acornassociated_location_area_types;
DROP TRIGGER IF EXISTS tr_acornassociated_location_addresses_server_id ON public.acornassociated_location_addresses;
DROP TRIGGER IF EXISTS tr_acornassociated_location_addresses_new_replicated_row ON public.acornassociated_location_addresses;
DROP INDEX IF EXISTS public.fki_type_id;
DROP INDEX IF EXISTS public.dr_acornassociated_location_types_replica_identity;
DROP INDEX IF EXISTS public.dr_acornassociated_location_location_replica_identity;
DROP INDEX IF EXISTS public.dr_acornassociated_location_gps_replica_identity;
DROP INDEX IF EXISTS public.dr_acornassociated_location_areas_replica_identity;
DROP INDEX IF EXISTS public.dr_acornassociated_location_area_types_replica_identity;
DROP INDEX IF EXISTS public.dr_acornassociated_location_addresses_replica_identity;
DROP TABLE IF EXISTS public.acornassociated_location_types;
DROP TABLE IF EXISTS public.acornassociated_location_lookup;
DROP TABLE IF EXISTS public.acornassociated_location_locations;
DROP TABLE IF EXISTS public.acornassociated_location_gps;
DROP TABLE IF EXISTS public.acornassociated_location_areas;
DROP TABLE IF EXISTS public.acornassociated_location_area_types;
DROP TABLE IF EXISTS public.acornassociated_location_addresses;
