# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acornassociated.location::lang.models.areatype.label

# Model Form Field configuration
form: $/acornassociated/location/models/areatype/fields.yaml

# Model Class name
modelClass: AcornAssociated\Location\Models\AreaType

# Default redirect location
defaultRedirect: acornassociated/locations/areatypes

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/locations/areatypes/update/:id
    redirectClose: acornassociated/locations/areatypes

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/locations/areatypes
    redirectClose: acornassociated/locations/areatypes

# Preview page
preview:
    title: backend::lang.form.preview_title
